services:
  - type: web
    name: render-signal-audio
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: HF_SPACE_URL
        value: "androidguy-speaker-diarization.hf.space"
      - key: LOG_LEVEL
        value: "INFO"
